### ISSUE TITLE
Upgrades can fail on the `pull` with `ERROR: for nginx  toomanyrequests: Rate exceeded`

### ISSUE THREAD

**Issue by dianabarsan** [medic/cht-upgrade-service#20]
When performing an upgrade, in order to reduce downtime, new images are first pulled locally, and the containers are replaces. 
However, the `pull` command can fail with a rate exceeded error: 
```
ERROR: for nginx  toomanyrequests: Rate exceeded
upgrade-cht-upgrade-service-1  | toomanyrequests: Rate exceeded
```

This appears to be an expected throttling error for unauthenticated requests: https://docs.aws.amazon.com/AmazonECR/latest/userguide/common-errors.html

I think the simplest way to fix this is to retry the pull in a rate exceeded error.

**Comment by dianabarsan** [comment]
This is ready for AT on `20-retry-pull`. 
To AT, please download the main docker-compose file: https://github.com/medic/cht-upgrade-service/blob/20-retry-pull/docker-compose.yml and replace the image tag to match the branch: `public.ecr.aws/s5s3h4s7/cht-upgrade-service:latest` -> `public.ecr.aws/s5s3h4s7/cht-upgrade-service:1.0.0-20-retry-pull.3310978977` 
Afterwards, please clear your docker cache to make sure you'll be downloading a bunch of images when upgrading. Then upgrade from one version of the CHT to another. 

We retry 100 times with a delay of one second between retries.

**Comment by mrjones-plip** [comment]
NB - this happened to me on first boot as well.  I had just `kill`ed and `rm`ed all my containers, and then run `docker-compose up` and I was baffled why no containers started. Then I saw a bunch of `toomanyrequests: Rate exceeded` in the logs.

I think a generic retry will fix all cases (cold boot and upgrade), but just noting the more general problem!

**Comment by dianabarsan** [comment]
There's already a PR that adds the retry in the cht-upgrade-service :) I linked it in the comment above.

**Comment by dianabarsan** [comment]
I _thought_ we were in the cht-core issue :) 
Yes, I'm aware. I tried to avoid this behavior. But I think that ultimately it's just a limitation of how docker-compose works. When given a docker-compose file, it starts pulling ALL images in the given config concurrently, and this hits the request limit of ECR. 
The only way that I saw the problem completely removed was by logging in to the ECR, authenticated requests get a different pull threshold.

**Comment by mrjones-plip** [comment]
Good stuff! Thanks for the updates.  

I'm sure you're aware, but so far 100% of the time the fix for me has been to just re-run the upgrade service which in turn retries the image downloads which succeed. The retry you and jkuester did in #21 looks just right - nice work!

**Comment by lorerod** [comment]
**Environment**
Client platform: MacOS
Browser: Firefox
Instance: Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-core.yml) and [cht-couchdb.yml ](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb.yml) 

**Reproduced on main** 
Steps to reproduce:
- Save cht-core.yml and cht-couchdb.yml in a folder on your PC.
- Save main branch [cht-upgrade service compose file](https://github.com/medic/cht-upgrade-service/blob/main/docker-compose.yml) in a different folder.
- Start cht-upgrade-service with:
`DOCKER_CONFIG_PATH=/Users/marialorenarodriguezviruel/medic-workspace/docker-files/#20/cht-core/aws_conf CHT_COMPOSE_PATH=/Users/marialorenarodriguezviruel/medic-workspace/docker-files/#20/cht-core COUCHDB_USER=admin COUCHDB_PASSWORD=password COUCHDB_SECRET=secret COUCHDB_DATA=/Users/marialorenarodriguezviruel/medic-workspace/docker-files/#20/cht-core/srv docker-compose -f docker-compose.yml up -d`
- After the CHT starts up, went to the upgrade page and tried to upgrade to`save-couchdb-creds (~4.0.0)`.
- On the upgrade page, I'm seeing `Error triggering update`.
<img width="1051" alt="Captura de Pantalla 2022-11-07 a la(s) 15 48 49" src="https://user-images.githubusercontent.com/21312057/200391964-65b2eebf-52f2-4cc3-b0d0-bca28e9f65bc.png">
- Check the upgrade service logs and see the following error:

![Captura de Pantalla 2022-11-07 a la(s) 15 48 31](https://user-images.githubusercontent.com/21312057/200392110-899d2f15-46a3-4003-b720-2beda98ecad2.png)

**Comment by lorerod** [comment]
**Environment**
Client platform: MacOS
Browser: Firefox
Instance: Local using [cht-core.yml](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-core.yml) and [cht-couchdb.yml ](https://staging.dev.medicmobile.org/_couch/builds/medic:medic:master/docker-compose/cht-couchdb.yml) 

**Fixed on branch** 
Steps to reproduce:
- Save cht-core.yml and cht-couchdb.yml in a folder on your PC.
- Save `20-retry-pull` branch [cht-upgrade service compose file](https://github.com/medic/cht-upgrade-service/blob/20-retry-pull/docker-compose.yml) in a different folder.
- Replace the image tag to match the branch: `public.ecr.aws/s5s3h4s7/cht-upgrade-service:latest` to `public.ecr.aws/s5s3h4s7/cht-upgrade-service:1.0.0-20-retry-pull.3310978977`
- Clear my docker cache 
- Start cht-upgrade-service with:
`DOCKER_CONFIG_PATH=/Users/marialorenarodriguezviruel/medic-workspace/docker-files/#20/cht-core/aws_conf CHT_COMPOSE_PATH=/Users/marialorenarodriguezviruel/medic-workspace/docker-files/#20/cht-core COUCHDB_USER=admin COUCHDB_PASSWORD=password COUCHDB_SECRET=secret COUCHDB_DATA=/Users/marialorenarodriguezviruel/medic-workspace/docker-files/#20/cht-core/srv docker-compose -f docker-compose.yml up -d`
- After the CHT starts up, went to the upgrade page and tried to upgrade to`save-couchdb-creds (~4.0.0)`.
- Upgrade page show the new version:
<img width="1053" alt="Captura de Pantalla 2022-11-07 a la(s) 16 42 43" src="https://user-images.githubusercontent.com/21312057/200400227-b3a3b75b-46c2-4b2f-bef7-0e7ebfd9372c.png">

- cht-upgrade-service log with no errors
