### ISSUE TITLE
docker-compose down fails with "error while removing network"

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-upgrade-service#25]
When following the [example usage steps](https://github.com/medic/cht-upgrade-service#example-usage), i can set up a CHT instance using this upgrade service.  The last call I can change to be detached: `docker-compose up -d`, which should allow me to stop all services with this call: `docker-compose down`.

Instead of stopping all the services, it stops the upgrade service only, and then returns an error (see below). 
If this is an expected outcome because of the way upgrade service starts the containers, we should update the docs on the best practice to start/stop/restart the services.

tested on 
* Ubuntu 20.04
* Docker Compose version v2.11.2
* Docker version 20.10.21, build baeda1f

```
$ docker-compose up -d
[+] Running 1/1
 ⠿ Container cht-4-first-run-cht-upgrade-service-1  Started                                                                                                                                   0.4s

$ docker ps --format '{{.Names}}'
cht-4-first-run-cht-upgrade-service-1
4-first-run_nginx_1
4-first-run_api_1
4-first-run_sentinel_1
4-first-run_healthcheck_1
4-first-run_haproxy_1
4-first-run_couchdb_1

$ docker-compose  down                                                                     
[+] Running 1/1
 ⠿ Container cht-4-first-run-cht-upgrade-service-1  Removed                                                                                                                                  10.3s
 ⠿ Network cht-net                                  Error                                                                                                                                     0.0s
failed to remove network cht-net: Error response from daemon: error while removing network: network cht-net id a944f33ce6b1b6b2023313c5775524c18e4e2bb686984358422721ba09feae81 has active endpoints

$ docker ps --format '{{.Names}}'
4-first-run_nginx_1
4-first-run_api_1
4-first-run_sentinel_1
4-first-run_healthcheck_1
4-first-run_haproxy_1
4-first-run_couchdb_1
```

**Comment by dianabarsan** [comment]
There's one word I can think of that best describes this: "compromises"

1. cht-upgrade-service needs to be on the same network as cht-everything-else
2. we _want_ cht-everything-else to own the network 
3. we want the cht-upgrade-service to start cht-everything-else
4. we did not want to take down cht-everything-else when taking down the upgrade service

One solution would have been to declare the network as external in all docker-compose files, and introduce a manual step to create it. At the point of development, this was the only argument for tagging the network as external. 

However, in more recent discussions, we concluded that setting the network as external is needed for self-hosted clustered CouchDb.

**Comment by mrjones-plip** [comment]
Thanks for all the background details @dianabarsan !  You and I even [touched on some of these](https://github.com/medic/cht-core/issues/7802#issuecomment-1269432310) before, so I should have remembered.  You do good work my friend!

Let's close this bug as it's working as designed. At a later date , we can document things like a graceful `down` call with something like `docker-compose -p PROJECT-NAME --env-file .env -f compose/cht-core.yml -f compose/cht-couchdb.yml down` - but given this is out of scope for upgrade service, all the more reason to close this up!
