### ISSUE TITLE
Publish multi-arch docker images to support Apple Silicon (arm64)

### ISSUE THREAD

**Issue by mrjones-plip** [medic/cht-upgrade-service#36]
Mac users running Docker Helper 4.x are seeing this error:

```
 Container 8841-dir-cht-upgrade-service-1                                                              Started0.1s
 ! cht-upgrade-service The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested 0.0s
```

The fix should be to publish `arm64` images [in CI](https://github.com/medic/cht-upgrade-service/blob/main/.github/workflows/test.yml) like we [did for CHT Core](https://github.com/medic/cht-core/issues/8277).

**Comment by dianabarsan** [comment]
Thanks @mrjones-plip .
The upgrade-service publishing is manual at the moment, so except for someone running the command to publish, nothing has to be done.

**Comment by dianabarsan** [comment]
😅 Well, scratch that. I totally added automated publishing for this one!!! (https://github.com/medic/cht-upgrade-service/blob/main/test/publish/index.js)

**Comment by mrjones-plip** [comment]
@1yuv - you interested in grabbing this ticket to [work your magic like last time](https://github.com/medic/cht-core/issues/8841)?

**Comment by 1yuv** [comment]
I will take look at this @mrjones-plip .

**Comment by mrjones-plip** [comment]
awesome - thanks @1yuv !
